spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/vsu_java
    username: vsu_java_dev
    password: vsu_java_dev
    driverClassName: org.postgresql.Driver