CREATE DATABASE vsu_java WITH TEMPLATE = template0 ;

ALTER DATABASE vsu_java OWNER TO postgres;

CREATE ROLE vsu_java_dev NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN PASSWORD 'vsu_java_dev';

CREATE SCHEMA vsu_java AUTHORIZATION vsu_java_dev;